// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Clarity",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Clarity",
            targets: ["AppModule"],
            bundleIdentifier: "org.academy.developer.Luca.Clarity",
            teamIdentifier: "CZ4F798NUV",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "Grant access to the camera to calculate PD distance and try on glasses in AR.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [.process("usdz")]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
